In [1]:
from io import StringIO
from csv import writer 
import pandas as pd
dhab = pd.read_csv('./Dados/dengue_por_habitante.csv.gz')
dhab = dhab[dhab['dt_sintoma']>= '2007'].reset_index()
dhab.index = dhab.UF
data_hoje_l = list(set(dhab[dhab['dt_sintoma']>='2007'].loc['RS'].dt_sintoma))
data_hoje_l.sort()
dist = pd.read_csv('distancia_UF.csv', index_col=0)
data_hoje1 = list(set(dhab[dhab['dt_sintoma']>='2010'].loc['RS'].dt_sintoma))
data_hoje1.sort()

In [2]:
#dhab é a tabela com os dados a partir de 2007, com as siglas dos estados como índice
dhab

,index,dt_sintoma,co_municipio,municipio,estado,UF,regiao,latitude,longitude,populacao,ocorrencias,por_habitante
UF,,,,,,,,,,,,
SE,366,2007-01-07,2800308,Aracaju,Sergipe,SE,Nordeste,-10.9091,-37.0677,547504.0,4,0.730588
SE,367,2007-01-14,2800308,Aracaju,Sergipe,SE,Nordeste,-10.9091,-37.0677,547717.0,5,0.912880
SE,368,2007-01-21,2800308,Aracaju,Sergipe,SE,Nordeste,-10.9091,-37.0677,547930.0,8,1.460041
SE,369,2007-01-28,2800308,Aracaju,Sergipe,SE,Nordeste,-10.9091,-37.0677,548143.0,0,0.000000
SE,370,2007-02-04,2800308,Aracaju,Sergipe,SE,Nordeste,-10.9091,-37.0677,548355.0,7,1.276545
...,...,...,...,...,...,...,...,...,...,...,...,...
ES,27270,2019-04-07,3205309,Vitória,Espírito Santo,ES,Sudeste,-20.3155,-40.3128,363218.0,196,53.962083
ES,27271,2019-04-14,3205309,Vitória,Espírito Santo,ES,Sudeste,-20.3155,-40.3128,363294.0,180,49.546648
ES,27272,2019-04-21,3205309,Vitória,Espírito Santo,ES,Sudeste,-20.3155,-40.3128,363369.0,194,53.389254
ES,27273,2019-04-28,3205309,Vitória,Espírito Santo,ES,Sudeste,-20.3155,-40.3128,363445.0,176,48.425484
ES,27274,2019-05-05,3205309,Vitória,Espírito Santo,ES,Sudeste,-20.3155,-40.3128,363520.0,46,12.654049

In [3]:
#A lista data_hoje_l contém todas as datas onde existem ocorrências.
data_hoje_l

['2007-01-07',
 '2007-01-14',
 '2007-01-21',
 '2007-01-28',
 '2007-02-04',
 '2007-02-11',
 '2007-02-18',
 '2007-02-25',
 '2007-03-04',
 '2007-03-11',
 '2007-03-18',
 '2007-03-25',
 '2007-04-01',
 '2007-04-08',
 '2007-04-15',
 '2007-04-22',
 '2007-04-29',
 '2007-05-06',
 '2007-05-13',
 '2007-05-20',
 '2007-05-27',
 '2007-06-03',
 '2007-06-10',
 '2007-06-17',
 '2007-06-24',
 '2007-07-01',
 '2007-07-08',
 '2007-07-15',
 '2007-07-22',
 '2007-07-29',
 '2007-08-05',
 '2007-08-12',
 '2007-08-19',
 '2007-08-26',
 '2007-09-02',
 '2007-09-09',
 '2007-09-16',
 '2007-09-23',
 '2007-09-30',
 '2007-10-07',
 '2007-10-14',
 '2007-10-21',
 '2007-10-28',
 '2007-11-04',
 '2007-11-11',
 '2007-11-18',
 '2007-11-25',
 '2007-12-02',
 '2007-12-09',
 '2007-12-16',
 '2007-12-23',
 '2007-12-30',
 '2008-01-06',
 '2008-01-13',
 '2008-01-20',
 '2008-01-27',
 '2008-02-03',
 '2008-02-10',
 '2008-02-17',
 '2008-02-24',
 '2008-03-02',
 '2008-03-09',
 '2008-03-16',
 '2008-03-23',
 '2008-03-30',
 '2008-04-06',
 '2008-04-13',
 '2008-04-20',
 '2008-04-27',
 '2008-05-04',
 '2008-05-11',
 '2008-05-18',
 '2008-05-25',
 '2008-06-01',
 '2008-06-08',
 '2008-06-15',
 '2008-06-22',
 '2008-06-29',
 '2008-07-06',
 '2008-07-13',
 '2008-07-20',
 '2008-07-27',
 '2008-08-03',
 '2008-08-10',
 '2008-08-17',
 '2008-08-24',
 '2008-08-31',
 '2008-09-07',
 '2008-09-14',
 '2008-09-21',
 '2008-09-28',
 '2008-10-05',
 '2008-10-12',
 '2008-10-19',
 '2008-10-26',
 '2008-11-02',
 '2008-11-09',
 '2008-11-16',
 '2008-11-23',
 '2008-11-30',
 '2008-12-07',
 '2008-12-14',
 '2008-12-21',
 '2008-12-28',
 '2009-01-04',
 '2009-01-11',
 '2009-01-18',
 '2009-01-25',
 '2009-02-01',
 '2009-02-08',
 '2009-02-15',
 '2009-02-22',
 '2009-03-01',
 '2009-03-08',
 '2009-03-15',
 '2009-03-22',
 '2009-03-29',
 '2009-04-05',
 '2009-04-12',
 '2009-04-19',
 '2009-04-26',
 '2009-05-03',
 '2009-05-10',
 '2009-05-17',
 '2009-05-24',
 '2009-05-31',
 '2009-06-07',
 '2009-06-14',
 '2009-06-21',
 '2009-06-28',
 '2009-07-05',
 '2009-07-12',
 '2009-07-19',
 '2009-07-26',
 '2009-08-02',
 '2009-08-09',
 '2009-08-16',
 '2009-08-23',
 '2009-08-30',
 '2009-09-06',
 '2009-09-13',
 '2009-09-20',
 '2009-09-27',
 '2009-10-04',
 '2009-10-11',
 '2009-10-18',
 '2009-10-25',
 '2009-11-01',
 '2009-11-08',
 '2009-11-15',
 '2009-11-22',
 '2009-11-29',
 '2009-12-06',
 '2009-12-13',
 '2009-12-20',
 '2009-12-27',
 '2010-01-03',
 '2010-01-10',
 '2010-01-17',
 '2010-01-24',
 '2010-01-31',
 '2010-02-07',
 '2010-02-14',
 '2010-02-21',
 '2010-02-28',
 '2010-03-07',
 '2010-03-14',
 '2010-03-21',
 '2010-03-28',
 '2010-04-04',
 '2010-04-11',
 '2010-04-18',
 '2010-04-25',
 '2010-05-02',
 '2010-05-09',
 '2010-05-16',
 '2010-05-23',
 '2010-05-30',
 '2010-06-06',
 '2010-06-13',
 '2010-06-20',
 '2010-06-27',
 '2010-07-04',
 '2010-07-11',
 '2010-07-18',
 '2010-07-25',
 '2010-08-01',
 '2010-08-08',
 '2010-08-15',
 '2010-08-22',
 '2010-08-29',
 '2010-09-05',
 '2010-09-12',
 '2010-09-19',
 '2010-09-26',
 '2010-10-03',
 '2010-10-10',
 '2010-10-17',
 '2010-10-24',
 '2010-10-31',
 '2010-11-07',
 '2010-11-14',
 '2010-11-21',
 '2010-11-28',
 '2010-12-05',
 '2010-12-12',
 '2010-12-19',
 '2010-12-26',
 '2011-01-02',
 '2011-01-09',
 '2011-01-16',
 '2011-01-23',
 '2011-01-30',
 '2011-02-06',
 '2011-02-13',
 '2011-02-20',
 '2011-02-27',
 '2011-03-06',
 '2011-03-13',
 '2011-03-20',
 '2011-03-27',
 '2011-04-03',
 '2011-04-10',
 '2011-04-17',
 '2011-04-24',
 '2011-05-01',
 '2011-05-08',
 '2011-05-15',
 '2011-05-22',
 '2011-05-29',
 '2011-06-05',
 '2011-06-12',
 '2011-06-19',
 '2011-06-26',
 '2011-07-03',
 '2011-07-10',
 '2011-07-17',
 '2011-07-24',
 '2011-07-31',
 '2011-08-07',
 '2011-08-14',
 '2011-08-21',
 '2011-08-28',
 '2011-09-04',
 '2011-09-11',
 '2011-09-18',
 '2011-09-25',
 '2011-10-02',
 '2011-10-09',
 '2011-10-16',
 '2011-10-23',
 '2011-10-30',
 '2011-11-06',
 '2011-11-13',
 '2011-11-20',
 '2011-11-27',
 '2011-12-04',
 '2011-12-11',
 '2011-12-18',
 '2011-12-25',
 '2012-01-01',
 '2012-01-08',
 '2012-01-15',
 '2012-01-22',
 '2012-01-29',
 '2012-02-05',
 '2012-02-12',
 '2012-02-19',
 '2012-02-26',
 '2012-03-04',
 '2012-03-11',
 '2012-03-18',
 '2012-03-25',
 '2012-04-01',
 '2012-04-08',
 '2012-04-15',
 '2012-04-22',
 '2012-04-29',
 '2012-05-06',
 '2012-05-13',
 '2012-05-20',
 '2012-05-27',
 '2012-06-03',
 '2012-06-10',
 '2012-06-17',
 '2012-06-24',
 '2012-07-01',
 '2012-07-08',
 '2012-07-15',
 '2012-07-22',
 '2012-07-29',
 '2012-08-05',
 '2012-08-12',
 '2012-08-19',
 '2012-08-26',
 '2012-09-02',
 '2012-09-09',
 '2012-09-16',
 '2012-09-23',
 '2012-09-30',
 '2012-10-07',
 '2012-10-14',
 '2012-10-21',
 '2012-10-28',
 '2012-11-04',
 '2012-11-11',
 '2012-11-18',
 '2012-11-25',
 '2012-12-02',
 '2012-12-09',
 '2012-12-16',
 '2012-12-23',
 '2012-12-30',
 '2013-01-06',
 '2013-01-13',
 '2013-01-20',
 '2013-01-27',
 '2013-02-03',
 '2013-02-10',
 '2013-02-17',
 '2013-02-24',
 '2013-03-03',
 '2013-03-10',
 '2013-03-17',
 '2013-03-24',
 '2013-03-31',
 '2013-04-07',
 '2013-04-14',
 '2013-04-21',
 '2013-04-28',
 '2013-05-05',
 '2013-05-12',
 '2013-05-19',
 '2013-05-26',
 '2013-06-02',
 '2013-06-09',
 '2013-06-16',
 '2013-06-23',
 '2013-06-30',
 '2013-07-07',
 '2013-07-14',
 '2013-07-21',
 '2013-07-28',
 '2013-08-04',
 '2013-08-11',
 '2013-08-18',
 '2013-08-25',
 '2013-09-01',
 '2013-09-08',
 '2013-09-15',
 '2013-09-22',
 '2013-09-29',
 '2013-10-06',
 '2013-10-13',
 '2013-10-20',
 '2013-10-27',
 '2013-11-03',
 '2013-11-10',
 '2013-11-17',
 '2013-11-24',
 '2013-12-01',
 '2013-12-08',
 '2013-12-15',
 '2013-12-22',
 '2013-12-29',
 '2014-01-05',
 '2014-01-12',
 '2014-01-19',
 '2014-01-26',
 '2014-02-02',
 '2014-02-09',
 '2014-02-16',
 '2014-02-23',
 '2014-03-02',
 '2014-03-09',
 '2014-03-16',
 '2014-03-23',
 '2014-03-30',
 '2014-04-06',
 '2014-04-13',
 '2014-04-20',
 '2014-04-27',
 '2014-05-04',
 '2014-05-11',
 '2014-05-18',
 '2014-05-25',
 '2014-06-01',
 '2014-06-08',
 '2014-06-15',
 '2014-06-22',
 '2014-06-29',
 '2014-07-06',
 '2014-07-13',
 '2014-07-20',
 '2014-07-27',
 '2014-08-03',
 '2014-08-10',
 '2014-08-17',
 '2014-08-24',
 '2014-08-31',
 '2014-09-07',
 '2014-09-14',
 '2014-09-21',
 '2014-09-28',
 '2014-10-05',
 '2014-10-12',
 '2014-10-19',
 '2014-10-26',
 '2014-11-02',
 '2014-11-09',
 '2014-11-16',
 '2014-11-23',
 '2014-11-30',
 '2014-12-07',
 '2014-12-14',
 '2014-12-21',
 '2014-12-28',
 '2015-01-04',
 '2015-01-11',
 '2015-01-18',
 '2015-01-25',
 '2015-02-01',
 '2015-02-08',
 '2015-02-15',
 '2015-02-22',
 '2015-03-01',
 '2015-03-08',
 '2015-03-15',
 '2015-03-22',
 '2015-03-29',
 '2015-04-05',
 '2015-04-12',
 '2015-04-19',
 '2015-04-26',
 '2015-05-03',
 '2015-05-10',
 '2015-05-17',
 '2015-05-24',
 '2015-05-31',
 '2015-06-07',
 '2015-06-14',
 '2015-06-21',
 '2015-06-28',
 '2015-07-05',
 '2015-07-12',
 '2015-07-19',
 '2015-07-26',
 '2015-08-02',
 '2015-08-09',
 '2015-08-16',
 '2015-08-23',
 '2015-08-30',
 '2015-09-06',
 '2015-09-13',
 '2015-09-20',
 '2015-09-27',
 '2015-10-04',
 '2015-10-11',
 '2015-10-18',
 '2015-10-25',
 '2015-11-01',
 '2015-11-08',
 '2015-11-15',
 '2015-11-22',
 '2015-11-29',
 '2015-12-06',
 '2015-12-13',
 '2015-12-20',
 '2015-12-27',
 '2016-01-03',
 '2016-01-10',
 '2016-01-17',
 '2016-01-24',
 '2016-01-31',
 '2016-02-07',
 '2016-02-14',
 '2016-02-21',
 '2016-02-28',
 '2016-03-06',
 '2016-03-13',
 '2016-03-20',
 '2016-03-27',
 '2016-04-03',
 '2016-04-10',
 '2016-04-17',
 '2016-04-24',
 '2016-05-01',
 '2016-05-08',
 '2016-05-15',
 '2016-05-22',
 '2016-05-29',
 '2016-06-05',
 '2016-06-12',
 '2016-06-19',
 '2016-06-26',
 '2016-07-03',
 '2016-07-10',
 '2016-07-17',
 '2016-07-24',
 '2016-07-31',
 '2016-08-07',
 '2016-08-14',
 '2016-08-21',
 '2016-08-28',
 '2016-09-04',
 '2016-09-11',
 '2016-09-18',
 '2016-09-25',
 '2016-10-02',
 '2016-10-09',
 '2016-10-16',
 '2016-10-23',
 '2016-10-30',
 '2016-11-06',
 '2016-11-13',
 '2016-11-20',
 '2016-11-27',
 '2016-12-04',
 '2016-12-11',
 '2016-12-18',
 '2016-12-25',
 '2017-01-01',
 '2017-01-08',
 '2017-01-15',
 '2017-01-22',
 '2017-01-29',
 '2017-02-05',
 '2017-02-12',
 '2017-02-19',
 '2017-02-26',
 '2017-03-05',
 '2017-03-12',
 '2017-03-19',
 '2017-03-26',
 '2017-04-02',
 '2017-04-09',
 '2017-04-16',
 '2017-04-23',
 '2017-04-30',
 '2017-05-07',
 '2017-05-14',
 '2017-05-21',
 '2017-05-28',
 '2017-06-04',
 '2017-06-11',
 '2017-06-18',
 '2017-06-25',
 '2017-07-02',
 '2017-07-09',
 '2017-07-16',
 '2017-07-23',
 '2017-07-30',
 '2017-08-06',
 '2017-08-13',
 '2017-08-20',
 '2017-08-27',
 '2017-09-03',
 '2017-09-10',
 '2017-09-17',
 '2017-09-24',
 '2017-10-01',
 '2017-10-08',
 '2017-10-15',
 '2017-10-22',
 '2017-10-29',
 '2017-11-05',
 '2017-11-12',
 '2017-11-19',
 '2017-11-26',
 '2017-12-03',
 '2017-12-10',
 '2017-12-17',
 '2017-12-24',
 '2017-12-31',
 '2018-01-07',
 '2018-01-14',
 '2018-01-21',
 '2018-01-28',
 '2018-02-04',
 '2018-02-11',
 '2018-02-18',
 '2018-02-25',
 '2018-03-04',
 '2018-03-11',
 '2018-03-18',
 '2018-03-25',
 '2018-04-01',
 '2018-04-08',
 '2018-04-15',
 '2018-04-22',
 '2018-04-29',
 '2018-05-06',
 '2018-05-13',
 '2018-05-20',
 '2018-05-27',
 '2018-06-03',
 '2018-06-10',
 '2018-06-17',
 '2018-06-24',
 '2018-07-01',
 '2018-07-08',
 '2018-07-15',
 '2018-07-22',
 '2018-07-29',
 '2018-08-05',
 '2018-08-12',
 '2018-08-19',
 '2018-08-26',
 '2018-09-02',
 '2018-09-09',
 '2018-09-16',
 '2018-09-23',
 '2018-09-30',
 '2018-10-07',
 '2018-10-14',
 '2018-10-21',
 '2018-10-28',
 '2018-11-04',
 '2018-11-11',
 '2018-11-18',
 '2018-11-25',
 '2018-12-02',
 '2018-12-09',
 '2018-12-16',
 '2018-12-23',
 '2018-12-30',
 '2019-01-06',
 '2019-01-13',
 '2019-01-20',
 '2019-01-27',
 '2019-02-03',
 '2019-02-10',
 '2019-02-17',
 '2019-02-24',
 '2019-03-03',
 '2019-03-10',
 '2019-03-17',
 '2019-03-24',
 '2019-03-31',
 '2019-04-07',
 '2019-04-14',
 '2019-04-21',
 '2019-04-28',
 '2019-05-05',
 '2019-05-12']

In [5]:
# Problema que fez meu código parar: A última data de 2019 não é igual para todos. Por exemplo:
dhab.loc['AP'].tail()

,index,dt_sintoma,co_municipio,municipio,estado,UF,regiao,latitude,longitude,populacao,ocorrencias,por_habitante
UF,,,,,,,,,,,,
AP,13126,2019-03-24,1600303,Macapá,Amapá,AP,Norte,0.034934,-51.0694,508474.0,26,5.113339
AP,13127,2019-03-31,1600303,Macapá,Amapá,AP,Norte,0.034934,-51.0694,508707.0,24,4.717843
AP,13128,2019-04-07,1600303,Macapá,Amapá,AP,Norte,0.034934,-51.0694,508940.0,25,4.912170
AP,13129,2019-04-14,1600303,Macapá,Amapá,AP,Norte,0.034934,-51.0694,509172.0,3,0.589192
AP,13130,2019-04-21,1600303,Macapá,Amapá,AP,Norte,0.034934,-51.0694,509405.0,1,0.196307

In [6]:
dhab.loc['RN'].tail()

,index,dt_sintoma,co_municipio,municipio,estado,UF,regiao,latitude,longitude,populacao,ocorrencias,por_habitante
UF,,,,,,,,,,,,
RN,16157,2019-04-07,2408102,Natal,Rio Grande do Norte,RN,Nordeste,-5.79357,-35.1986,889181.0,366,41.161473
RN,16158,2019-04-14,2408102,Natal,Rio Grande do Norte,RN,Nordeste,-5.79357,-35.1986,889356.0,349,39.241878
RN,16159,2019-04-21,2408102,Natal,Rio Grande do Norte,RN,Nordeste,-5.79357,-35.1986,889531.0,322,36.198851
RN,16160,2019-04-28,2408102,Natal,Rio Grande do Norte,RN,Nordeste,-5.79357,-35.1986,889706.0,79,8.879338
RN,16161,2019-05-05,2408102,Natal,Rio Grande do Norte,RN,Nordeste,-5.79357,-35.1986,889881.0,12,1.348495

In [9]:
# Eu escolhi a maior data existente, mas foi um erro, devemos escolher a menor data 
# para evitar fazermos uma query em uma data e estado que não estão presentes na tabela. 
# Talvez existam outras datas que não estão em todas as linhas da tabela??

#Essa é a tabela com as distâncias. Eu fiz 3 versões, uma com os índices sendo a sigla dos estados, outra com os municípios
#e outra com os códigos. A com a sigla é mais fácil de trabalhar.

dist.head()

,SE,MG,PA,RR,DF,MS,MT,PR,SC,CE,...,RS,RO,PE,AC,RJ,BA,MA,SP,PI,ES
SE,0.00,1.62,2.02,5.45,1.66,2.70,2.71,2.58,2.86,1.11,...,3.30,4.17,0.50,3.43,1.84,0.32,1.55,2.18,1.11,1.36
MG,1.62,0.00,2.70,4.70,0.73,1.28,1.57,0.99,1.27,2.38,...,1.71,3.03,2.10,2.85,0.44,1.43,2.64,0.59,2.30,0.52
PA,2.02,2.70,0.00,3.84,1.98,2.83,2.51,3.19,3.57,1.50,...,4.01,2.57,2.03,2.40,3.13,2.05,0.58,2.90,0.91,3.19
RR,5.45,4.72,3.84,0.00,4.21,3.84,3.13,4.84,5.13,4.98,...,5.25,1.67,5.46,1.66,5.07,5.65,4.32,4.68,4.39,5.23
DF,1.66,0.73,1.98,4.19,0.00,1.05,1.06,1.39,1.67,2.12,...,2.11,2.52,2.14,2.31,1.16,1.46,2.03,1.00,1.68,1.25

In [10]:
#Essa lista compreende as datas onde começaremos a analisar as cidades, pois a prinípio voltaremos 3 anos para cada cidade,
#ou seja, devemos começar a partir de 2010

data_hoje1

['2010-01-03',
 '2010-01-10',
 '2010-01-17',
 '2010-01-24',
 '2010-01-31',
 '2010-02-07',
 '2010-02-14',
 '2010-02-21',
 '2010-02-28',
 '2010-03-07',
 '2010-03-14',
 '2010-03-21',
 '2010-03-28',
 '2010-04-04',
 '2010-04-11',
 '2010-04-18',
 '2010-04-25',
 '2010-05-02',
 '2010-05-09',
 '2010-05-16',
 '2010-05-23',
 '2010-05-30',
 '2010-06-06',
 '2010-06-13',
 '2010-06-20',
 '2010-06-27',
 '2010-07-04',
 '2010-07-11',
 '2010-07-18',
 '2010-07-25',
 '2010-08-01',
 '2010-08-08',
 '2010-08-15',
 '2010-08-22',
 '2010-08-29',
 '2010-09-05',
 '2010-09-12',
 '2010-09-19',
 '2010-09-26',
 '2010-10-03',
 '2010-10-10',
 '2010-10-17',
 '2010-10-24',
 '2010-10-31',
 '2010-11-07',
 '2010-11-14',
 '2010-11-21',
 '2010-11-28',
 '2010-12-05',
 '2010-12-12',
 '2010-12-19',
 '2010-12-26',
 '2011-01-02',
 '2011-01-09',
 '2011-01-16',
 '2011-01-23',
 '2011-01-30',
 '2011-02-06',
 '2011-02-13',
 '2011-02-20',
 '2011-02-27',
 '2011-03-06',
 '2011-03-13',
 '2011-03-20',
 '2011-03-27',
 '2011-04-03',
 '2011-04-10',
 '2011-04-17',
 '2011-04-24',
 '2011-05-01',
 '2011-05-08',
 '2011-05-15',
 '2011-05-22',
 '2011-05-29',
 '2011-06-05',
 '2011-06-12',
 '2011-06-19',
 '2011-06-26',
 '2011-07-03',
 '2011-07-10',
 '2011-07-17',
 '2011-07-24',
 '2011-07-31',
 '2011-08-07',
 '2011-08-14',
 '2011-08-21',
 '2011-08-28',
 '2011-09-04',
 '2011-09-11',
 '2011-09-18',
 '2011-09-25',
 '2011-10-02',
 '2011-10-09',
 '2011-10-16',
 '2011-10-23',
 '2011-10-30',
 '2011-11-06',
 '2011-11-13',
 '2011-11-20',
 '2011-11-27',
 '2011-12-04',
 '2011-12-11',
 '2011-12-18',
 '2011-12-25',
 '2012-01-01',
 '2012-01-08',
 '2012-01-15',
 '2012-01-22',
 '2012-01-29',
 '2012-02-05',
 '2012-02-12',
 '2012-02-19',
 '2012-02-26',
 '2012-03-04',
 '2012-03-11',
 '2012-03-18',
 '2012-03-25',
 '2012-04-01',
 '2012-04-08',
 '2012-04-15',
 '2012-04-22',
 '2012-04-29',
 '2012-05-06',
 '2012-05-13',
 '2012-05-20',
 '2012-05-27',
 '2012-06-03',
 '2012-06-10',
 '2012-06-17',
 '2012-06-24',
 '2012-07-01',
 '2012-07-08',
 '2012-07-15',
 '2012-07-22',
 '2012-07-29',
 '2012-08-05',
 '2012-08-12',
 '2012-08-19',
 '2012-08-26',
 '2012-09-02',
 '2012-09-09',
 '2012-09-16',
 '2012-09-23',
 '2012-09-30',
 '2012-10-07',
 '2012-10-14',
 '2012-10-21',
 '2012-10-28',
 '2012-11-04',
 '2012-11-11',
 '2012-11-18',
 '2012-11-25',
 '2012-12-02',
 '2012-12-09',
 '2012-12-16',
 '2012-12-23',
 '2012-12-30',
 '2013-01-06',
 '2013-01-13',
 '2013-01-20',
 '2013-01-27',
 '2013-02-03',
 '2013-02-10',
 '2013-02-17',
 '2013-02-24',
 '2013-03-03',
 '2013-03-10',
 '2013-03-17',
 '2013-03-24',
 '2013-03-31',
 '2013-04-07',
 '2013-04-14',
 '2013-04-21',
 '2013-04-28',
 '2013-05-05',
 '2013-05-12',
 '2013-05-19',
 '2013-05-26',
 '2013-06-02',
 '2013-06-09',
 '2013-06-16',
 '2013-06-23',
 '2013-06-30',
 '2013-07-07',
 '2013-07-14',
 '2013-07-21',
 '2013-07-28',
 '2013-08-04',
 '2013-08-11',
 '2013-08-18',
 '2013-08-25',
 '2013-09-01',
 '2013-09-08',
 '2013-09-15',
 '2013-09-22',
 '2013-09-29',
 '2013-10-06',
 '2013-10-13',
 '2013-10-20',
 '2013-10-27',
 '2013-11-03',
 '2013-11-10',
 '2013-11-17',
 '2013-11-24',
 '2013-12-01',
 '2013-12-08',
 '2013-12-15',
 '2013-12-22',
 '2013-12-29',
 '2014-01-05',
 '2014-01-12',
 '2014-01-19',
 '2014-01-26',
 '2014-02-02',
 '2014-02-09',
 '2014-02-16',
 '2014-02-23',
 '2014-03-02',
 '2014-03-09',
 '2014-03-16',
 '2014-03-23',
 '2014-03-30',
 '2014-04-06',
 '2014-04-13',
 '2014-04-20',
 '2014-04-27',
 '2014-05-04',
 '2014-05-11',
 '2014-05-18',
 '2014-05-25',
 '2014-06-01',
 '2014-06-08',
 '2014-06-15',
 '2014-06-22',
 '2014-06-29',
 '2014-07-06',
 '2014-07-13',
 '2014-07-20',
 '2014-07-27',
 '2014-08-03',
 '2014-08-10',
 '2014-08-17',
 '2014-08-24',
 '2014-08-31',
 '2014-09-07',
 '2014-09-14',
 '2014-09-21',
 '2014-09-28',
 '2014-10-05',
 '2014-10-12',
 '2014-10-19',
 '2014-10-26',
 '2014-11-02',
 '2014-11-09',
 '2014-11-16',
 '2014-11-23',
 '2014-11-30',
 '2014-12-07',
 '2014-12-14',
 '2014-12-21',
 '2014-12-28',
 '2015-01-04',
 '2015-01-11',
 '2015-01-18',
 '2015-01-25',
 '2015-02-01',
 '2015-02-08',
 '2015-02-15',
 '2015-02-22',
 '2015-03-01',
 '2015-03-08',
 '2015-03-15',
 '2015-03-22',
 '2015-03-29',
 '2015-04-05',
 '2015-04-12',
 '2015-04-19',
 '2015-04-26',
 '2015-05-03',
 '2015-05-10',
 '2015-05-17',
 '2015-05-24',
 '2015-05-31',
 '2015-06-07',
 '2015-06-14',
 '2015-06-21',
 '2015-06-28',
 '2015-07-05',
 '2015-07-12',
 '2015-07-19',
 '2015-07-26',
 '2015-08-02',
 '2015-08-09',
 '2015-08-16',
 '2015-08-23',
 '2015-08-30',
 '2015-09-06',
 '2015-09-13',
 '2015-09-20',
 '2015-09-27',
 '2015-10-04',
 '2015-10-11',
 '2015-10-18',
 '2015-10-25',
 '2015-11-01',
 '2015-11-08',
 '2015-11-15',
 '2015-11-22',
 '2015-11-29',
 '2015-12-06',
 '2015-12-13',
 '2015-12-20',
 '2015-12-27',
 '2016-01-03',
 '2016-01-10',
 '2016-01-17',
 '2016-01-24',
 '2016-01-31',
 '2016-02-07',
 '2016-02-14',
 '2016-02-21',
 '2016-02-28',
 '2016-03-06',
 '2016-03-13',
 '2016-03-20',
 '2016-03-27',
 '2016-04-03',
 '2016-04-10',
 '2016-04-17',
 '2016-04-24',
 '2016-05-01',
 '2016-05-08',
 '2016-05-15',
 '2016-05-22',
 '2016-05-29',
 '2016-06-05',
 '2016-06-12',
 '2016-06-19',
 '2016-06-26',
 '2016-07-03',
 '2016-07-10',
 '2016-07-17',
 '2016-07-24',
 '2016-07-31',
 '2016-08-07',
 '2016-08-14',
 '2016-08-21',
 '2016-08-28',
 '2016-09-04',
 '2016-09-11',
 '2016-09-18',
 '2016-09-25',
 '2016-10-02',
 '2016-10-09',
 '2016-10-16',
 '2016-10-23',
 '2016-10-30',
 '2016-11-06',
 '2016-11-13',
 '2016-11-20',
 '2016-11-27',
 '2016-12-04',
 '2016-12-11',
 '2016-12-18',
 '2016-12-25',
 '2017-01-01',
 '2017-01-08',
 '2017-01-15',
 '2017-01-22',
 '2017-01-29',
 '2017-02-05',
 '2017-02-12',
 '2017-02-19',
 '2017-02-26',
 '2017-03-05',
 '2017-03-12',
 '2017-03-19',
 '2017-03-26',
 '2017-04-02',
 '2017-04-09',
 '2017-04-16',
 '2017-04-23',
 '2017-04-30',
 '2017-05-07',
 '2017-05-14',
 '2017-05-21',
 '2017-05-28',
 '2017-06-04',
 '2017-06-11',
 '2017-06-18',
 '2017-06-25',
 '2017-07-02',
 '2017-07-09',
 '2017-07-16',
 '2017-07-23',
 '2017-07-30',
 '2017-08-06',
 '2017-08-13',
 '2017-08-20',
 '2017-08-27',
 '2017-09-03',
 '2017-09-10',
 '2017-09-17',
 '2017-09-24',
 '2017-10-01',
 '2017-10-08',
 '2017-10-15',
 '2017-10-22',
 '2017-10-29',
 '2017-11-05',
 '2017-11-12',
 '2017-11-19',
 '2017-11-26',
 '2017-12-03',
 '2017-12-10',
 '2017-12-17',
 '2017-12-24',
 '2017-12-31',
 '2018-01-07',
 '2018-01-14',
 '2018-01-21',
 '2018-01-28',
 '2018-02-04',
 '2018-02-11',
 '2018-02-18',
 '2018-02-25',
 '2018-03-04',
 '2018-03-11',
 '2018-03-18',
 '2018-03-25',
 '2018-04-01',
 '2018-04-08',
 '2018-04-15',
 '2018-04-22',
 '2018-04-29',
 '2018-05-06',
 '2018-05-13',
 '2018-05-20',
 '2018-05-27',
 '2018-06-03',
 '2018-06-10',
 '2018-06-17',
 '2018-06-24',
 '2018-07-01',
 '2018-07-08',
 '2018-07-15',
 '2018-07-22',
 '2018-07-29',
 '2018-08-05',
 '2018-08-12',
 '2018-08-19',
 '2018-08-26',
 '2018-09-02',
 '2018-09-09',
 '2018-09-16',
 '2018-09-23',
 '2018-09-30',
 '2018-10-07',
 '2018-10-14',
 '2018-10-21',
 '2018-10-28',
 '2018-11-04',
 '2018-11-11',
 '2018-11-18',
 '2018-11-25',
 '2018-12-02',
 '2018-12-09',
 '2018-12-16',
 '2018-12-23',
 '2018-12-30',
 '2019-01-06',
 '2019-01-13',
 '2019-01-20',
 '2019-01-27',
 '2019-02-03',
 '2019-02-10',
 '2019-02-17',
 '2019-02-24',
 '2019-03-03',
 '2019-03-10',
 '2019-03-17',
 '2019-03-24',
 '2019-03-31',
 '2019-04-07',
 '2019-04-14',
 '2019-04-21',
 '2019-04-28',
 '2019-05-05',
 '2019-05-12']

In [12]:
output = StringIO() #Cria uma instância de string na memória
csv_writer = writer(output) # Permite escrever em csv nessa string. Tudo acontece na memória RAM, como o trabalho é apenas
                            # inserir strings (1 byte) na memória RAM, isso é muito mais rápido do que trabalhar diretamente
                            # com o pandas, pois o tipo de dado DataFrame é custoso e o pandas muitas vezes precisa realocar
                            # o DataFrame todo para uma posição na memória RAM onde contenha mais espaço vazio, para adicionar
                            # novos dados. Por isso a inserção de dados no pandas fica cada vez mais lenta. Pelo que li,
                            # esse método é 1000x mais rápido que com o pandas e não fica mais lento com o tempo.

# Quando o pandas lê o csv, a primeira linha do arquivo é o que ele naturalmente coloca como o nome das colunas.
# Por isso, inicialmente já escrevo as colunas no output
csv_writer.writerow(['cidade_alvo','data_hoje',
                     'ocorrencia_hoje','janela_ano',
                     'date_janela','ocorrencia_janela',
                     'cidade_pred','distancia',
                     'lag_semana','date_lag',
                     'ocorrencia_pred'])


#O valor que ele imprime é a posição do ponteiro na memória. Como ele imprimiu 138, significa que o arquivo tem 137 chars.

138

In [ ]:
for cidade_alvo in set(dhab.index): # começo fixando a cidade alvo
    for data_hoje in data_hoje1: # fixo a data que analisaremos com respeito à cidade alvo
        for janela in range(1,4): # aqui fixo a janela, de 1 a 3 anos
            for cidade_pred in set(dhab.index): # percorre as cidades que serão as preditoras (não exclui a prpópria cidade, mas excluir pode poupar algumas horas)
                for lag_pred in range(0,157): # agora percorro o lag da cidade preditora, de 0 semanas até 156 semanas
                    janelaData = data_hoje_l[data_hoje_l.index(data_hoje)-52*janela] # aqui guardo a data referente à janela que existe na planilha, 
                                                                                     # voltando 52*janela índices na lista, ou seja 52*janela semanas
                    lagData = data_hoje_l[data_hoje_l.index(data_hoje)-lag_pred] # mesma coisa, só que com a data do lag
                    # a row é escrita como uma lista em python, na ordem das colunas que existe no csv:
                    row = [cidade_alvo,
                           data_hoje,
                           dhab[dhab['dt_sintoma']==data_hoje].loc[cidade_alvo]['ocorrencias'],
                           janela,
                           janelaData,
                           dhab[dhab['dt_sintoma']==janelaData].loc[cidade_alvo]['ocorrencias'],
                           cidade_pred,
                           dist.loc[cidade_alvo,cidade_pred],
                           lag_pred,
                           lagData,
                           dhab[dhab['dt_sintoma']==lagData].loc[cidade_pred]['ocorrencias']]
                    csv_writer.writerow(row)

In [13]:
# Quando o trabalho termina, o ponteiro de leitura está no final da string, portanto precisamos retornar
# ao primeiro char para então ler com o pandas e depois salvar no HD.

output.seek(0)
df = pd.read_csv(output)
df.to_csv('dados_final.csv')

In [ ]:
# Problemas: 

# Não imagino uma maneira eficiente de fazer backups pelo processo. Não sei se funciona salvar e depois continuar,
# pois mexemos no ponteiro de escrita e pode bagunçar tudo. Uma opção talvez seja fazer um try except e gravar os parametros
# cidade_alvo, data_hoje, janela etc. em algum arquivo txt, para analisar os possíveis erros e também para podermos começar de onde paramos.

# Como escrevi em cima, as vezes a data que fazemos a query não existe para o determinado estado, eu comecei a percorrer 
# a lista de datas ao invés de fazer aritmética com as datas por causa disso, pois aquelas datas existem no dataframe.
# Algumas vezes, se você subtrai 7 dias de uma data, ela não está presente no dataframe. 
# COntudo, as últimas datas de 2019 não são iguais para todos e fatalmente dará problema. Solução: pegar a menor das datas
# Talvez existam outras datas assim pelo dataset? Acho que é interessante fazer um try/except e bolarmos uma maneira de
# lidarmos com esse problema, procurar a data mais próxima que existe?

In [15]:
# Só para ilustrar como fica:
output = StringIO()
csv_writer = writer(output)
csv_writer.writerow(['cidade_alvo','data_hoje',
                     'ocorrencia_hoje','janela_ano',
                     'date_janela','ocorrencia_janela',
                     'cidade_pred','distancia',
                     'lag_semana','date_lag',
                     'ocorrencia_pred'])
output.seek(0)
df = pd.read_csv(output)
df
# Um cuidado: como ele escreve apenas as strings, ele vai ignorar qualquer erro de formatação.
# Os erros que podemos perceber são referentes às querys.

Empty DataFrame
Columns: [cidade_alvo, data_hoje, ocorrencia_hoje, janela_ano, date_janela, ocorrencia_janela, cidade_pred, distancia, lag_semana, date_lag, ocorrencia_pred]
Index: []